const
mm/percpu.c:2168:20: error: pcpu_fc_names causes a section type conflict
with dt_supported_cpu_ops
 const char * const pcpu_fc_names[PCPU_FC_NR] __initconst = {
                     ^
		     arch/arm64/kernel/cpu_ops.c:34:37: note:
		     ‘dt_supported_cpu_ops’ was declared here
		      static const struct cpu_operations
		      *dt_supported_cpu_ops[] __initconst = {